### ISSUE TITLE
List of converter errors from GL 29-30

### ISSUE THREAD

**Issue by bkrawiec** [CopticScriptorium/converters#1]
@ctschroeder 

Ú      ̈

v       ϣ

C       ϭ

> ```
>   ·
> ```

S       ⲏ

H       ϩ

=       ̄

c       ⲭ

T       ϯ

c±     ⲭ︤

P       ̂

/       ̣

F       ϥ

x       ⲝ

C       ϭ

~       ́

y       ⲯ

†     ⲧ̄

**Comment by ctschroeder** [comment]
Did you use the CopticLS parameter?

**Comment by bkrawiec** [comment]
No. Where is that described? I read "read me" but did not see the parameter (I see the update saying you added it, but did not realize it was something I was to use).

**Comment by ctschroeder** [comment]
https://docs.google.com/document/d/16fvkKDN9bXXw5ArnI6lYF8K7b_BnBFuvos7FjoqE8tc/edit?usp=docslist_api

**Comment by bkrawiec** [comment]
I remembered the phone call discussion but then when I did not see it in "read me" thought I had misunderstood what a parameter meant. Missed the google doc. Got it for next conversion.

**Comment by ctschroeder** [comment]
If you want me to add all the parameters to the Readme doc, please make an issue.

**Comment by bkrawiec** [comment]
OK. For me, I can just follow the work flow of the google doc. But since the converter repository is not private--meaning anyone can fork it, right?--I think it is best to be in "read me" in case someone else is using it.
